dynamodb_access = 'AKIA5J3JYYIHEBWVKAUF'
dynamodb_secret = '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'
dynamodb_region = 'us-east-2'
dynamodb_table = 'prod_assist'
openai_key = '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'
model = 'gpt-4-0613'